### ISSUE TITLE
Shared Styles

### ISSUE THREAD

**Issue by TimPietrusky** [NERDDISCO/luminave#67]
Instead of defining the same styles in every component over and over again, it should be shared  and imported. 

See https://polymer.github.io/pwa-starter-kit/configuring-and-personalizing/#sharing-styles

## ToDo
- [x] Remove dark-side theme and add a real theme
- [x] Use shared styled for grid and flex
- [x] Use CSS variables for theming
- [x] Remove old CSS variables to have just one theme
