### ISSUE TITLE
Add fixtures for dotJS 2018

### ISSUE THREAD

**Issue by TimPietrusky** [NERDDISCO/luminave#91]
Add all fixtures that are needed for dotJS 2018:

- [x] [MAC Quantum Wash](https://adn.harmanpro.com/site_elements/executables/6727_1526699470/UM_MACQuantumWash_EN_C_original.pdf)
- [x] [Viper VL3000 Spot](http://www.vari-lite.com/clientuploads/directory/downloads/VL3000_User_A.pdf)
- [x] [MAC Aura](https://adn.harmanpro.com/site_elements/executables/6756_1526699610/UM_MACAura_EN_B_original.pdf)

## ToDo

- [ ] Extend fivetwelve to allow *CombinedChannelParam* to handle multiple channels with the same value (for example beamDimmer + auraDimmer for MAC Aura)

**Comment by TimPietrusky** [comment]
I opened https://github.com/beyondscreen/fivetwelve/issues/2 to track the CombinedChannelParam idea.
